### ISSUE TITLE
Failed to run the first test after installing docker image  

### ISSUE THREAD

**Issue by koala819** [ousamabenyounes/docker-yellowlabtools#29]
With @ousamabenyounes I found a bug when runing first docker instance

To fix it, I killed this first docker instance and I relaunched it and everything is OK

**Comment by youvalteboul** [comment]
Salut @ousamabenyounes,

je voudrais scanner mon env local et j'ai le meme problème, mais meme après un restart ca plante encore.

```

Phantomas failed: Failed to launch the browser process! Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted [0420/154004.084201:FATAL:zygote_host_impl_linux.cc(191)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). Received signal 6 r8: 00007ffcf8ced6f0 r9: 00007f38857eff6c r10: 0000000000000008 r11: 0000000000000246 r12: 00007ffcf8cedd20 r13: 00007ffcf8cedc5c r14: 00007f3883781ca0 r15: 00000000000000a0 di: 0000000000000002 si: 00007ffcf8ced5a0 bp: 00007ffcf8ced5a0 bx: 0000000000000000 dx: 0000000000000000 ax: 0000000000000000 cx: 00007f38891e03b2 sp: 00007ffcf8ced598 ip: 00007f38891e03b2 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000 [end of stack trace] Calling _exit(1). Core file will not be generated. TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

sur mon local, mon url est pas `localhost` mais j'ai un nom de domaine `local.monsite.com`, je sais pas si ca peut jouer

**Comment by ousamabenyounes** [comment]
Coucou @youvalteboul jespere que tu vas bien! désolé pour ce délai de réponse, je suis en arret maladie :( je patiente...
du coup je voulais savoir si tu as reussi à lancer ton instance locale? sinon on s'appel pour échange (linkedIn message si tu es ok? en esperant que tout va bien pour toi)

**Comment by ousamabenyounes** [comment]
fixed with our latest docker image
 just docker pull ousamabenyounes/yellowlabtools to get latest YLT V3 docker image!
