### ISSUE TITLE
Bug with command line to activate DEBUG mode

### ISSUE THREAD

**Issue by xgeno** [ousamabenyounes/docker-yellowlabtools#30]
This line is incorrect

` docker run  --privileged --env DEBUG=* -p 8383:8383 ousamabenyounes/yellowlabtools`
 
 It's necessary to add '' to obtain 
 
`  docker run  --privileged --env 'DEBUG=*' -p 8383:8383 ousamabenyounes/yellowlabtools`

**Comment by ousamabenyounes** [comment]
Thank you for this fix and sorry for the issue. 
Can you open a Pull Request so you'll add this on the repository :)
