### ISSUE TITLE
Test stuck, how to kill one test?

### ISSUE THREAD

**Issue by planetahuevo** [ousamabenyounes/docker-yellowlabtools#33]
One test was stuck and it did not kill it automatically after 20 minutes. 
So I could not do any other tests. 

So, how do I kill tests that are stuck using the command line (or any other way)?

Thanks

**Comment by ousamabenyounes** [comment]
A test should not take more that 1 or 2 minute to be available.
This seems to be a bug on this version of our docker image.
I recommand you to restart or kill docker container and launch it again your test.

`docker ps` will show you the docker container reference
so you will be able to run `docker restart CONTAINER_ID`
or `docker kill CONTAINER_ID`

Hope this will make your local test working

Good luck

**Comment by planetahuevo** [comment]
Hi, 
Thanks, but that will kill the container completely and all tests that are "on the queue" will be deleted as well. 
This is what I did, because there was no other way to make it work, but I wonder: 

Is there any way to kill the one that has been stuck without killing the whole container? 
I am able to bash into the container, but I was not sure what process to kill.

**Comment by ousamabenyounes** [comment]
You're right, it could be better to be able to kill only the specific test if you are able to run other tests .
For this I ping @gmetais  Maybe he could give you a better recommandation to stop a specific running test 

Good luck!

**Comment by planetahuevo** [comment]
Thank you! 
I was thinking if we can have a supervisor or something checking for the queue and kill or remove from the queue the ones that are stuck. 
I also was suprised to see that one stuck test blocks the whole process for anyone. I thought we could have multiple test running at the same time... but those are discussion for another day. :)

Thank you very much for building this and @gmetais for the whole tool!

**Comment by ousamabenyounes** [comment]
It is a great pleasure for me 
This is the main difference between cloud solution (split-branch) and the actual docker image.
One process for all running test...so you have a queue...and the online solution, 
realeased by @gmetais and @ohoareau removed this feature so you can run multiple test at same moment...
this was a great feature and now online we never have to wait other web user test running so great and cool :)
but the docker image didn't get this precious update for the moment :)
