### ISSUE TITLE
Docker using develop branch and version 2.1.0

### ISSUE THREAD

**Issue by planetahuevo** [ousamabenyounes/docker-yellowlabtools#34]
Hi, 
I noticed that the server is still using the "non-split" server on branch develop and checkout e9ab1fd  
Do you plan to update this image in the future? 

Thanks

**Comment by ousamabenyounes** [comment]
Hi @planetahuevo thanks for reporting this issue.
The split server branch is dedicated to the online tool wich now use specific cloud features.
That's why it is not planned to use this branch for the moment.
Regards

**Comment by planetahuevo** [comment]
So the recommended docker installation is not following the same code as the main branch. 
It is a pity. I will try a manual installation then. 

Thank you for the fast reply.

**Comment by ousamabenyounes** [comment]
I agree with you that it would be REALLY better I think to stay connected on the split branch
But maybe we will change this on the futur.
And if you succeeded to do this I will be very happy to try it and accept it on the docker image!
I have some health problem so i can't maintain the docker image for the moment i'm sorry.

Using different branch make it realy difficult to stay connected between bug fixes and new features....

what do you think about this @gmetais

**Comment by planetahuevo** [comment]
Do not worry. 
This comment suggest it can be run with the manual service:
https://github.com/YellowLabTools/YellowLabTools-server/issues/2
I tried and got a lot of errors during the "npm install" command but I think my nodejs version is the latest 18, and not the 14, so probably that was my mistake. 
Maybe a good moment to try to create a docker image myself. 
I will give it a try during the holidays and let you know. :)

**Comment by ousamabenyounes** [comment]
Thank you and good luck and good vacations also! :)

**Comment by gmetais** [comment]
> what do you think about this @gmetais

Yes, absolutely. I need to free some time to finish the split and merge everything with the cloud version.
